### ISSUE TITLE
max_size doesn't seem to work.

### ISSUE THREAD

**Issue by ziazek** [transloadit/rails-sdk#26]
I tried putting max_size in the transloadit.yml file like this:

``` yaml
auth:
  key     : '418...'
  secret  : '660...'
  duration: 1800 # 30 minute validity period for signed upload forms
  max_size: 2097152

templates: ...
```

I can't get it to work. According to the [Authentication](https://transloadit.com/docs/authentication) page in the docs 

> You need to use max_size in the hidden params field of your form. 

I've tried adding a hidden field in the form named "max_size" but it doesn't work either.

Is there a way to set a maximum file size?
