### ISSUE TITLE
/file/filter robot

### ISSUE THREAD

**Issue by guillosaracco** [transloadit/rails-sdk#45]
Hi,

I've been trying to make the /file/filter robot work with my rails app and failing. 
I haven't found any useful ruby on rails examples in the Transloadit docs.
I would like some help on how to use the /file/filter robot to decline a file larger than 10MB using ruby on rails.

Thank you

**Comment by kvz** [comment]
Hi,

Just add a first step with something like this:

**Comment by tim-kos** [comment]
Hey @guillosaracco 

did you see @kvz 's reply?

**Comment by rmehner** [comment]
To amend on @kvz's reply, in your `config/transloadit.yml` you could do something like this:

```yaml
templates:
  filter_files:
    steps:
      filter:
        use: ":original"
        robot: "/file/filter"
        declines:
        - - "${file.size}"
          - ">"
          - '10485760'
        error_on_decline: true
```

obviously it makes sense to add a second step to work with the filtered results. To be used in your app like this then:

```
<%= form_for Model.new, :html => { :id => 'upload' } do |form| %>
  <%= transloadit :filter_files %>
  <%= form.label :file, 'File to upload' %>
  <%= form.file_field :file %>
  <%= form.submit %>
<% end %>
<%= transloadit_jquerify :upload, :wait => true %>
```
