### ISSUE TITLE
Dynamic fields not working in template

### ISSUE THREAD

**Issue by koriner** [transloadit/rails-sdk#50]
I'm trying to update my transloadit templates to use some more dynamic fields from the html form (Rails, Rackspace cloud files, transloadit_jquerify etc), however the ```fields``` object doesn't seem to contain the values I'm passing.

The template is set up like this:
```
store:
          use: ['optimized']
          robot: '/cloudfiles/store'
          container: *rs_container
          user: *rs_user
          key: *rs_key
          data_center: *rs_data_center
          account_type: *rs_account_type
          path: "images/${fields.item_category}/${file.id}_${file.url_name}"
```

and my HTML form contains the following:
```
<%= form_for item, :url => form_url, :html => { :id => 'upload_image' } do |form| %>
  <%= transloadit :image_upload %>
  <%= form.label :file, 'File to upload' %>
  <%= form.file_field :file, :accept => "image/jpg, image/jpeg, image/png" %>
  <%= form.label :name, "Description" %>
  <input type="text" name="name" id="name"/>

  <!-- I have tried both options for creating a hidden field -->
  <%= form.hidden_field 'item_category', :value => item_category %>
  <input type="hidden" name="item_category" id="item_category" value="<%= item_category %>" />
  
  <%= form.submit 'Upload Image', :id => "submitBtnImage" %>
<% end %>

<%= transloadit_jquerify :upload_image, :wait => true, :processZeroFiles => false %>
```

But the ```item_category``` is always empty or nil, resulting in a file path like ```images//XXX_file.jpg```

Any ideas what I'm doing wrong here?
